- src/App.js
- src/page/ListPage.jsx
- src/page/UserSigninpage.jsx
> Env: "라우트 세팅 추가"

- src/App.js
- src/components/Header/Header.jsx
- src/components/Header/style.js
- src/page/HomePage/HomePage.jsx
- src/page/UserSigninpage/UserSigninpage.jsx
- src/page/UserSignuppage/UserSignuppage.jsx
> Env: "글로벌 스타일 추가"

- src/components/OwnerSignin/OwnerSignin.jsx
- src/components/OwnerSignin/style.js
- src/components/UserSignin/style.js
- src/page/SignupSelectPage/style.js
- src/page/UserSigninpage/UserSigninpage.jsx
- src/page/UserSigninpage/style.js
> Design : "로그인 디자인 버튼 추가"

- package-lock.json
- src/components/OwnerSignin/style.js
- src/components/UserSignin/style.js
- src/page/UserSigninpage/style.js
> Design: "로그인 디자인 수정"

- src/App.js
- src/page/UserSigninpage/UserSigninpage.jsx
> Design: "디자인2차수정"

- package-lock.json
- package.json
- src/App.js
- src/apis/SearchAdress.jsx
- src/apis/style.js
- src/components/Header/Header.jsx
- src/components/UserSignin/style.js
- src/page/SignupPage/OwnerSignupPage/OwnerSignupPage.jsx
- src/page/SignupPage/OwnerSignupPage/style.js
- src/page/SignupPage/UserSignupPage/UserSignupPage.jsx
- src/page/SignupPage/UserSignupPage/style.js
- src/page/SignupSelectPage/SignupSelectPage.jsx
- src/page/UserSigninPage/style.js
> Design: "회원가입 화면 css 적용"

- package-lock.json
- src/components/Header/Header.jsx
- src/components/OwnerSignin/OwnerSignin.jsx
- src/components/UserSignin/UserSignin.jsx
- src/page/SignupPage/OwnerSignupPage/OwnerSignupPage.jsx
- src/page/SignupPage/OwnerSignupPage/style.js
- src/page/SignupPage/UserSignupPage/UserSignupPage.jsx
- src/page/SignupPage/UserSignupPage/style.js
- src/page/SignupSelectPage/SignupSelectPage.jsx
> Design: "로그인/회원가입"

- src/apis/writeBoardApi.js
- src/page/Board/BoardPage/BoardPage.jsx
- src/page/Board/WritePage/WritePage.jsx
- src/page/Board/WritePage/style.js
- 제목, 내용을 입력하고 작성하기를 누르면 DB에 게시글이 저장됨
- 성공적으로 DB에 저장되면 alert 창을 띄어서 알려줌
- alert창이 뜬 후 해당 게시글의 detail 페이지로 이동
> Feat: 게시글 작성 기능 구현

- src/App.js
- src/apis/modifyBoardApi.js
- src/page/Board/DetailPage/DetailPage.jsx
- src/page/Board/ModifyPage/ModifyPage.jsx
- src/page/Board/ModifyPage/style.js
- src/page/Board/WritePage/WritePage.jsx
- 게시글에서 수정 버튼을 누르면 수정 페이지로 들어가서 게시글을 수정할 수 있다. 
- 취소를 누르면 해당 게시글 상세 페이지로 돌아간다.
> Feat: 게시글 수정 기능 추가

- src/page/Board/BoardPage/style.js
- src/page/Board/ModifyPage/ModifyPage.jsx
- src/page/Board/ModifyPage/style.js
- src/page/Board/WritePage/WritePage.jsx
이미지 업로드가 되도록 FireBase 규칙을 바꿨음.
> Fix: Quill 에디터 이미지 업로드 기능

- src/page/MapPage/MapPage.jsx
> 24-10-11 Feat: "카페  리스트 불러오기"

- public/index.html
> 24-10-11 Fix: "프론트 콘솔창 경고문 수정"

- src/page/MapPage/MapPage.jsx
> 24-10-11 Feat: "카페 검색기능 추가"

- public/index.html
- src/page/MapPage/MapPage.jsx
> 24-10-11 Fix: "index.html 카카오 키 추가"

- src/page/Board/BoardPage/BoardPage.jsx
- 검색창에 아무것도 입력하지 않고 검색버튼을 누르면 전체리스트를 가져옴.
- 필터를 설정하고 검색하면 필터에 해당하는 게시글만 불러옴.
> Feat: 게시글 검색 기능 구현

- src/page/MapPage/MapPage.jsx
> 24-10-11 Feat: "카페 리스트 마커"

- src/components/Comments/Comments.jsx
댓글 입력란에 댓글을 작성하고 작성하기를 누르면 댓글이 작성되어 댓글란에
보여지게 됨.
> Feat: 댓글 작성 기능 구현

- src/components/Comments/Comments.jsx
댓글 삭제 버튼을 누르면 댓글을 삭제할건지 물어보는 alert 창이 뜨고, "확인" 버튼을 눌러야 댓글이 삭제됨.
> Feat: 댓글 삭제 기능 구현

- src/components/Cafelist/Cafelist.jsx
- src/components/Cafelist/style.js
- src/components/CustomMarker/CustomMarker.jsx
- src/components/SearchBox/SearchBox.jsx
- src/components/SearchBox/style.js
- src/page/MapPage/MapPage.jsx
> 24-10-15 Refactor: "지도 component 빼기"

- package-lock.json
- package.json
- src/page/MapPage/MapPage.jsx
- src/page/MapPage/style.js
> 24-10-16 Feat: "지도 디자인 수정"

- src/components/SelectCategory/style.js
- src/page/CafeListPage/CafeListPage.jsx
- src/page/CafeListPage/style.js
- src/page/MapPage/MapPage.jsx
- src/page/MapPage/style.js
> 24-10-20 Style:"지도, list css 변경"

- src/page/Manager/ManagerManagementPage/ManagerManagementPage.jsx
- src/page/Manager/ManagerManagementPage/style.js
> 24-10-21 Feat: "매니저 페이지"

- src/App.js
- src/page/Manager/ManagerStoreManagementPage/ManagerStoreManagementPage.jsx
- src/page/Manager/ManagerStoreManagementPage/style.js
> 24-10-21 Feat: "매니저 페이지-점포관리"

- src/page/MapPage/MapPage.jsx
- src/page/MapPage/style.js
> 24-10-21 Feat: "지도 css 수정"

- src/page/Manager/ManagerManagementPage/ManagerManagementPage.jsx
- src/page/Manager/ManagerManagementPage/style.js
- src/page/Manager/ManagerStoreManagementPage/ManagerStoreManagementPage.jsx
- src/page/MapPage/style.js
> 24-10-22 Feat: "관리자 css 수정"

- src/page/Manager/ManagerManagementPage/ManagerManagementPage.jsx
> 24-10-23 Feat:"유저 기록 가져오기"

- package-lock.json
- package.json
- src/App.js
- src/components/Info/BoardInfo/BoardInfo.jsx
- src/components/Info/CommentInfo/CommentInfo.jsx
- src/components/Info/ReviewInfo/ReviewInfo.jsx
- src/components/Info/UserInfo/UserInfo.jsx
- src/components/Info/UserInfo/style.js
- src/components/Manager/ManagerMainLayout/style.js
- src/components/UserContent/UserContent.jsx
- src/page/Manager/ManagerManagementPage/ManagerManagementPage.jsx
- src/page/Manager/ManagerManagementPage/style.js
> 24-10-23 Feat:"관리자"

- src/components/Info/BoardInfo/BoardInfo.jsx
- src/components/Info/BoardInfo/style.js
- src/components/Info/CommentInfo/CommentInfo.jsx
- src/components/Info/CommentInfo/style.js
- src/components/Info/ReviewInfo/ReviewInfo.jsx
- src/components/Info/ReviewInfo/style.js
- src/components/Info/UserInfo/UserInfo.jsx
- src/components/Info/UserInfo/style.js
- src/page/Manager/ManagerManagementPage/style.js
> 24-10-23 Feat:"관리자 css 수정"

- src/App.js
- src/apis/CafeApis/modifyCafeBannerApi.js
- src/page/Board/DetailPage/DetailPage.jsx
- src/page/Cafe/CafeDetailPage/style.js
- src/page/Cafe/CafeListPage/CafeListPage.jsx
- src/page/Cafe/CafeListPage/style.js
- src/page/Owner/CafeModifyPage/CafeModifyPage.jsx
- src/page/Owner/CafeModifyPage/style.js
- src/page/Owner/OwnerMyPage/OwnerMyPage.jsx
- src/page/Owner/OwnerMyPage/style.js
점주 페이지 css 작업 완료, 카페 정보 수정 기능 구현 완료, 카페 배너 이미지 설정 및 수정 기능 구현 완료
> Feat: 점주 페이지 css 작업

- src/page/MapPage/MapPage.jsx
- src/page/MapPage/style.js
카페 배너에 카페 이미지 표시하도록 수정, 카페 배너 클릭 시 해당 카페
상세 페이지로 이동하도록 수정
> Design: 지도 카페배너 수정
